### PR TITLE
Update styling on hunt session (control panel) page

### PR DESCRIPTION
**Pull request by lloydtao**
Changes have been made to the .php page and the relevant .js file (Vue component).

Specification with integration tests at: https://docs.google.com/document/d/1Eiv3dvpUYZhPJJajC-MqJ0imwwZ6siWXzWnAfQdPiCY

### CODE REVIEW

**Review by JakubKwak — CHANGES_REQUESTED** [review]
Can you make it so the photo submission is always in the centre? Currently, if I upload a tall image to sticks to the left side of the window.
Also, can you add some sort of separation to the teams in the leaderboard? Like a border on each item in the list or alternating background colours?

**Comment by lloydtao** [comment]
toxic

**Comment by lloydtao** [comment]
working on it

**Review by JakubKwak — APPROVED** [review]
very good work lewis

**Pull request merged**
