### PR TITLE
Password Requirements

### PR DESCRIPTION
**Pull request by JakubKwak**

### CODE REVIEW

**Comment by lloydtao** [comment]
Testing now :)

**Comment by lloydtao** [comment]
On regular browser, unit tests passing and integration tests have all passed.

However, NBP does not seem to load on incognito.

**Review by lloydtao — CHANGES_REQUESTED** [review]
Unit tests and integration tests fail in incognito mode. NBP does not seem to load.

**Review by lloydtao — APPROVED** [review]
All are just the missing lists of bad password. All good.

**Comment by lloydtao** [comment]
Changes approved. Re-testing.

**Review by lloydtao — CHANGES_REQUESTED** [review]
My good friend, please add lists to unit test folder too.

**Comment by lloydtao** [comment]
Testing now, friend.

**Comment by Joseph-Lintern** [comment]
Taken over validation

**Comment by Joseph-Lintern** [comment]
All unit tests and integration tests passed

**Pull request merged**
