### PR TITLE
Sql prepared statements

### PR DESCRIPTION
**Pull request by mf470**
Converting SQL statements to prepared SQL statements in all file except api files

### CODE REVIEW

**Comment by mf470** [comment]
Ready for review

**Comment by lloydtao** [comment]
File changes look good at first glance. Validating integration tests.

**Review by lloydtao — CHANGES_REQUESTED** [review]
Integration test 2 fails due to registerhandler.php line 69.

False is sent as string `'False'` rather than as boolean `False` (i.e. `(?, ?, ?, False);`).

**Review by lloydtao — APPROVED** [review]
All integration tests pass after updating `'False'` to `False`. Approving.

**Pull request merged**
