### PR TITLE
New submit loc

### PR DESCRIPTION
**Pull request by marektancak0106**

### CODE REVIEW

**Review by JakubKwak — CHANGES_REQUESTED** [review]
Make submit location button disappear when: answering a question, no questions left
Fix hardcoded team name and game pin.
stop the "all locations completed" popup from appearing
display directions instead of objective name

**Review by JakubKwak — CHANGES_REQUESTED** [review]
2 more things:
completing an objective (that is completed false) should give the team 100 score, currently no score is added.
Also, after completing the last objective, the page did not say I have completed the last objective and it did not hide the directions/location button. Something went wrong here I guess?

**Review by JakubKwak — APPROVED** [review]
seems to work fine, passed tests

**Comment by jsbaasi** [comment]
lgtm

**Pull request merged**
